services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_MAX=10
      # - USER_AGENT=
      # - PROXY=
    ports:
      - "3000:3000"
    depends_on:
      - redis

